logger:
  format: json
  level: debug

postgres:
  max_conns: 10
  max_lifetime: 30s

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  iddle_timeout: 60s
  
jwt:
  private_key_path: ./keys/private.pem
  public_key_path: ./keys/public.pem
  issuer: mock-auth
  audience: xakat0n-api
  key_id: mock-key-1
  ttl: 1h

shutdown_timeout: 30s
checkout_timer: 300s