logger:
  format: text
  level: debug

postgres:
  max_conns: 10
  max_lifetime: 30s

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  iddle_timeout: 60s

queue:
  purchase_window: 3s

shutdown_timeout: 30s