services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - "${PG_PORT:-5433}:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - xakat0n

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    build:
      context: ./migrator
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - ./migrator/internal/configs/migrator.yml:/app/config.yml:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - xakat0n

volumes:
  db_data:

networks:
  xakat0n:
    driver: bridge
