services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - "${PG_PORT:-5433}:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - xakat0n

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DB_URL: ${DB_URL}
      JWT_PRIVATE_KEY_PATH: ${JWT_PRIVATE_KEY_PATH:-/app/keys/private.pem}
      JWT_PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_PATH:-/app/keys/public.pem}
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./backend/internal/configs/backend.yml:/app/config.yml:ro
      - ./backend/keys/private.pem:/app/keys/private.pem:ro
      - ./backend/keys/public.pem:/app/keys/public.pem:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - xakat0n
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started 
    networks:
      - xakat0n
    environment:
      - VITE_API_URL=http://backend:8080
    restart: unless-stopped
  migrator:
    build:
      context: ./migrator
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - ./migrator/internal/configs/migrator.yml:/app/config.yml:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - xakat0n

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.125.0
    container_name: victoriametrics
    volumes:
      - vmdata:/storage
      - ./metrics/promscrape.yml:/etc/promscrape.yml
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--promscrape.config=/etc/promscrape.yml"
    ports:
      - "8428:8428"
    restart: unless-stopped
    networks:
      - xakat0n

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    depends_on:
      - victoriametrics
    ports:
      - "${GRAFANA_PORT:-4000}:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./metrics/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - xakat0n

volumes:
  db_data:
  vmdata:
  grafanadata:

networks:
  xakat0n:
    driver: bridge
